### PR TITLE
Update strings (& settings description)

### LINKED ISSUE #65: Show in new gallery
"From imageDetail-view you can open a new gallery view" it was answered upon my question in the translation system.
Just tried it in the app, but don't really see it's purpose. You can only have one gallery open at a time, no (it's not that there's two or more tabs that you can have different galleries open with).

Can you explain? :)

### LINKED ISSUE #67: Difference "sort_by_xxx" and "sort_order_xxx"
There's a long list of 'sorting' strings. What's the difference between "sort_by_xxx" and "sort_order_xxx"?

Seems to me like they can/should be merged? In version 0.5.2 only "sort_by_xxx" seems to be used?

 +	<string name="sort_by_date">Date</string>
 +	<string name="sort_by_folder">Folder</string>
 +	<string name="sort_by_name">Name</string>
 +	<string name="sort_by_name_len">Length</string>
 +	<string name="sort_by_none">Unsorted</string>
 +	<string name="sort_by_place">Place</string>
 +	<string name="sort_menu_title">Sort</string>
 +	<string name="sort_order_Date_Ascending">Date ascending</string>
 +	<string name="sort_order_Date_Descending">Date descending</string>
 +	<string name="sort_order_Name_Ascending">Name ascending</string>
 +	<string name="sort_order_Name_Descending">Name descending</string>
 +	<string name="sort_order_Name_length_Ascending">Name-length ascending</string>
 +	<string name="sort_order_Name_length_Descending">Name-length descending</string>

### PR DESCRIPTION
**Pull request by keunes**
Closes #65 & closes #67.

### CODE REVIEW

**Comment by k3b** [comment]
hello keunes. thanks for the changes.

I will look at the changes when i start preparing for a new fdroid-release.

I already added the new strings from https://crowdin.com/project/androFotoFinder/activity_stream until 2016-09-09.

Currently i have some bigger issues i want to finish before i start something new (i.e. look at your changes).

**Comment by k3b** [comment]
Note: The language names should keep code/english-text/native-text in case that you accidently changed language and want to go back to your language and donot understand.

if you see "ja japanese 日本人" instead of only  "日本人" you might guess that this could be the setting for the language.

I once had that problem when i accidently changed language to arabic and struggled to find the menu to switch language back to german ;-)

**Comment by keunes** [comment]
> if you see "ja japanese 日本人" instead of only "日本人" you might guess that this could be the setting for the language

Hmm. Don't like the easthetics of this solution, but I adapted it. Now thinking: maybe the app should always display the English string after the localised string for this particular setting; for example "Sprache (language)" or "Taal (language)". That way the user (provided they speak English) would not even have to _guess_ the correct setting.

Even still, it's merely a matter of trying all options of the overflow menu if I've set the language to Japanese and want to find the settings. Adding English names of languages nor my solution described above will help in this situation. I'm even wondering why users would want to be able to choose the language?

**Comment by k3b** [comment]
@keunes 

Thankyou for taking the time for doing the wording-fixes.

I approved all but this

* show_in_gallery_menu_title=Show in **new** gallery

because it opens up a new child gallery - the parent-gallery with it-s current filter-settings is still below the new child gallery. if you close the child gallery the parent-gallery (with it-s own filter settings) ist restored.

I have to check in the next days on my handset if no new text has gotten to long for a small screen. 

it may take some time until the new text appears on the translation site ....

**Pull request merged**
